### ISSUE TITLE
🔨 [feature] GPT 서비스 개발

### ISSUE THREAD

**Issue by LeeJinSeok323** [fianlProjectTeam2/server#16]
# 🤖 기능 개요
GPT API를 가져와서 AI 주가 예측 모델을 서비스를 통해 호출하고 예측값을 DB에 저장하는 기능을 만든다.
## ✅ Todo
- [x] GPT API 연동 테스팅하기
- [ ] 기사 헤드라인 기반 AI 주가 예측 모델 서비스
- [ ] 체결 정보 기반 AI 주가 예측 모델 서비스
