### ISSUE TITLE
🔨 [feature] 게시판 댓글, 추천기능 개발

### ISSUE THREAD

**Issue by zhurong5** [fianlProjectTeam2/server#19]
# 🤖 기능 개요
게시판 댓글기능, 게시글 추천기능, 예외처리 구현

## ✅ Todo
- [x] 게시글 목록에서 작성자의 별명이 표시되도록 수정
- [x] 로그인하지 않은 사용자가 글을 작성하려고 할 때 예외 처리
- [x] 글 작성 및 수정 시 예외 처리
- [x] 본인 글만 수정 및 삭제 가능하도록 기능 구현
- [x] 추천 기능 구현 (한 게시물에 대해 한 번만 추천)
- [x]  댓글 작성 및 삭제 기능 구현
